// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmubeXTdCqPmbL5GcIzaZUalRs4N_Culk',
    appId: '1:310435962057:android:b053d5437916dcef61c118',
    messagingSenderId: '310435962057',
    projectId: 'flutter-fire-test-1e22a',
    storageBucket: 'flutter-fire-test-1e22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBayrBCXriE5LGxOJIAUtEO-nO62y9W_Gw',
    appId: '1:310435962057:ios:d68fa22b45bb797161c118',
    messagingSenderId: '310435962057',
    projectId: 'flutter-fire-test-1e22a',
    storageBucket: 'flutter-fire-test-1e22a.appspot.com',
    iosClientId: '310435962057-16bul0uh25upn3ls65olvmnnvam9ljr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFire',
  );
}
